# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0004_auto_20170803_1259'),
        ('subventions', '0007_auto_20170729_2334'),
        ('vos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vos',
            name='mandat_ptr',
        ),
        migrations.RemoveField(
            model_name='vos',
            name='section',
        ),
        migrations.AlterField(
            model_name='encaissement',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binets.Mandat'),
        ),
        migrations.AlterField(
            model_name='montantcheque',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binets.Mandat'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binets.Mandat'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binets.Mandat'),
        ),
        migrations.DeleteModel(
            name='VOS',
        ),
    ]
