# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vos', '0003_auto_20170815_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaissement',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vos.EleveVos'),
        ),
    ]
